batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202311211754
train_epochs: 1000
train_workers: 20
vocab: '&xThaHQU#EMuvc1F"VANGz7eCBSm.p43y8Ll?!qf:k(PY2swXrD5n0O6*tIZb,;g/JjWK-+Ri
  ''d)9o'
width: 1408
